version: "3.7"
services:
  upstream-1:
    hostname: upstream-1
    build:
      context: ./upstream/ws
      dockerfile: Dockerfile
    environment:
      - PORT=8787
      - MEET=meet-457
      - REDIRECT=upstream-3
    ports:
      - "8787:8787"
    networks:
      - web
  upstream-2:
    hostname: upstream-2
    build:
      context: ./upstream/ws
      dockerfile: Dockerfile
    environment:
      - PORT=8788
      - MEET=meet-123
      - REDIRECT=upstream-3
    ports:
      - "8788:8788"
    networks:
      - web
  upstream-3:
    hostname: upstream-3
    build:
      context: ./upstream/ws
      dockerfile: Dockerfile
    environment:
      - PORT=8789
      - MEET=meet-127
      - REDIRECT=upstream-1
    ports:
      - "8789:8789"
    networks:
      - web
  envoy:
    image: envoyproxy/envoy:v1.26.3
    command: envoy --log-level warn -c /etc/envoy/envoy.yaml
    ports:
      - "8000:8000"
    volumes:
      - ./config/redirect.yaml:/etc/envoy/envoy.yaml
    networks:
      - web

volumes:
  redis:
    driver: local
networks:
  web:
    name: shared-web
    driver: bridge
    external: true
