static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
#               https://github.com/envoyproxy/envoy/issues/19578
                upgrade_configs:
                  - upgrade_type: websocket
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: upstream
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/meetings"
                          route:
                            cluster: upstream
                            hash_policy:
                              - header:
                                  header_name: x-meeting-id
                            internal_redirect_policy:
                              allow_cross_scheme_redirect: true
                              max_internal_redirects: 10
                        - match:
                            prefix: "/redirect"
                          route:
                            cluster_header: host
                            prefix_rewrite: /meetings
                            internal_redirect_policy:
                              allow_cross_scheme_redirect: true
                              max_internal_redirects: 10
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: upstream
      type: STRICT_DNS
      lb_policy: MAGLEV
      health_checks:
        - interval: 1s
          timeout: 2s
          unhealthy_threshold: 2
          healthy_threshold: 1
          http_health_check:
            path: /health
            expected_statuses:
              - start: 200
                end: 205
      load_assignment:
        cluster_name: upstream
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: upstream-1
                      port_value: 8787
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "upstream-1"
              - endpoint:
                  address:
                    socket_address:
                      address: upstream-2
                      port_value: 8788
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "upstream-2"
    - name: upstream-3
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - interval: 1s
          timeout: 2s
          unhealthy_threshold: 2
          healthy_threshold: 1
          http_health_check:
            path: /health
            expected_statuses:
              - start: 200
                end: 205
      load_assignment:
        cluster_name: upstream-3
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: upstream-3
                      port_value: 8789
